language: php
sudo: required
dist: trusty
group: edge

cache:
  directories:
    - $HOME/.composer/cache

php:

  - 5.6
  - 7.1

matrix:
    fast_finish: true
env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=4.0.*

before_install:
  - composer self-update
  - composer require --no-update symfony/expression-language "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/yaml "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/routing "$SYMFONY_VERSION"
  - composer require --no-update --dev symfony/dependency-injection "$SYMFONY_VERSION"

install:
    - composer install --no-interaction --prefer-dist

script:
    - ./bin/phpunit --coverage-text
